"""
breaker.py
Created on 2/16/26

Copyright (C) 2026 Mehmet Bertan Tarakcioglu

This file is part of OTP Dictionary Breaker.

OTP Dictionary Breaker is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License
as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

OTP Dictionary Breaker is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with OTP Dictionary Breaker.
If not, see <https://www.gnu.org/licenses/>.
"""

import re
from collections import defaultdict
from importlib import resources


class OTPDictBreaker:
    def __init__(
            self,
            common_words_list,
            ciphertexts,
            plaintext_has_numbers = True,
            plaintext_has_punctuation = True,
            remove_single_letters_from_common_words=True,
            number_top_candidates_to_try = 2,
            max_decipher_iters = 100
    ):
        """
        :param common_words_list:
        A string list of most commonly used words in English, sorted by frequency. Not case-sensitive. If unspecified,
        it will just use a built-in list of 10,000 words from the Google Web Trillion Word Corpus (recommended).

        :param ciphertexts:
        A string list containing any number of ciphertexts in hexadecimal format representing ASCII code bytes
        that were encrypted using the same One-Time-Pad key.

        :param plaintext_has_numbers:
        Set this to False if you don't think your plaintext will contain any punctuation. True by default.

        :param plaintext_has_punctuation:
        Set this to False if you don't think your plaintext will contain any numbers. True by default.

        :param remove_single_letters_from_common_words:
        When true, all single-letters are removed from the common words dataset generated by the common_words_path,
        and replaced only with 'a' and 'i'. True by default, and highly recommended for datasets based on internet usage.

        :param number_top_candidates_to_try:
        For each word with unknown spaces, the algorithm comes up with a list of dictionary words that will best fit. By default, we try
        2 of the best candidates and give up if they both don't fit. You can set this to any number between 1-10, inclusive.
        2-3 seems to work the best for accuracy, but feel free to experiment!

        :param max_decipher_iters: The maximum iteration limit for our decipher loop. Sometimes, the ciphertexts will result in an infinite loop
        because it will always find something to change in the key! There could be a better solution to this
        problem, but this works pretty reliably for now. Set to 100 by default.
        """

        # Define private and public variables
        self._msg_count = 0
        self._key_len = 0

        self.common_words_dict = defaultdict(list)
        self.ciphertexts = []
        self.maybe_key = []
        self.maybe_plaintexts = []

        self.plaintext_has_numbers = plaintext_has_numbers
        self.plaintext_has_punctuation = plaintext_has_punctuation

        if not (1 <= number_top_candidates_to_try <= 10):
            raise ValueError("Error: The number of top candidates to try must be between 1 and 10, inclusive!")

        if not (max_decipher_iters > 0):
            raise ValueError("Error: The number of maximum iterations must be at least 1!")

        self.number_top_candidates_to_try = number_top_candidates_to_try
        self.max_decipher_iters = max_decipher_iters

        # Initialize default word list if none was provided
        if common_words_list is None:
            common_words_list = []
            common_words_file = str(resources.files("otp_dict_breaker").joinpath("data", "google-10000-english.txt"))
            try:
                with open(common_words_file, 'r') as words_file:
                    for line in words_file:
                        common_words_list.append(line.strip().lower())
            except Exception:
                print(f"\033[1;91mError: Could not open built-in common words file. ",
                       "This is most likely an internal bug with the OTPDictBreaker module! Please consider reporting it :)\033[0m")
                raise
        elif len(common_words_list) == 0:
            raise ValueError("Error: The provided common words list seems to be empty.")

        # Now, convert the word list into a dictionary keyed by word length
        for word in common_words_list:
            self.common_words_dict[len(word)].append(word)

        # In a lot of these datasets based on web data, letters by themselves exist because
        # of the internet being the internet... This should fix it.
        if remove_single_letters_from_common_words: self.common_words_dict[1] = ['a', 'i']

        if len(ciphertexts) == 0:
            raise ValueError("Error: Could not find any ciphertexts to decipher.")

        # Convert the ciphertexts into arrays of bytes so we can do XOR on them
        self.ciphertexts = []
        for i, ctxt in enumerate(ciphertexts):
            ctxt = ctxt.strip()
            if len(ctxt) == 0:
                print(len(ctxt))
                raise ValueError(f"Error: Ciphertext with index {i} seems to be empty.")
            elif len(ctxt) % 2 == 1:
                raise ValueError(f"Error: Ciphertext with index {i} contains an odd number of characters. " +
                                 "Valid hexadecimal byte is expected to always contain an even number of characters, please try again.")
            try:
                self.ciphertexts.append(bytes.fromhex(ctxt))
            except Exception as e:
                raise ValueError(f"Error: Could not load data in ciphertext with index {i}: {e}. " +
                                  "Please make sure your file only contains valid hexadecimal byte data!")

        # Remember how many messages we have
        self._msg_count = len(self.ciphertexts)

        # Find the maximum key length we can use, in case the messages are not the same length
        self._key_len = min(map(lambda x: len(x), self.ciphertexts))

        # Fill the empty key with None
        self.maybe_key = [None] * self._key_len

    # Function to test if a byte falls within a valid ASCII range.
    # Customizable to include punctuation
    @staticmethod
    def _is_english_ascii(b: int, allow_numbers=False, allow_punctuation=False):
        return (
                b == 0x20        or  # space
                (65 <= b <= 90)  or  # A-Z
                (97 <= b <= 122) or  # a-z

                (allow_numbers and (48 <= b <= 57))  or  # 0-9

                (allow_punctuation and b in (
                    0x2C, 0x2E, 0x27, 0x21,  # , . ' !
                    0x3F, 0x3A, 0x3B, 0x2D,  # ? : ; -
                    0x22, 0x28, 0x29  # " ( )
                )))

    # Regular old crib dragging attack for multi-time-pad. This is the starting point of our attack.
    def no_dict_guess(self):
        # Assume everything is a space, and only accept it as a space if it works out on all the ciphertexts on the same index
        for k in range(self._key_len):
            for i, ctxt in enumerate(self.ciphertexts):
                guess = ctxt[k] ^ 0x20

                if all(self._is_english_ascii(self.ciphertexts[j][k] ^ guess)
                       for j in range(self._msg_count) if j != i):
                    self.maybe_key[k] = guess
                    break

    def update_plaintexts(self):
        """
        Calculate the plaintexts using the current key and the acceptable ASCII rules set,
        put hash signs (#) where valid ASCII cannot be calculated to a given byte.
        """
        self.maybe_plaintexts.clear()

        for ctxt in self.ciphertexts:
            plaintext = ""
            for k in range(self._key_len):
                if self.maybe_key[k] is not None:
                    ascii_num = ctxt[k] ^ self.maybe_key[k]
                    if self._is_english_ascii(ascii_num, self.plaintext_has_numbers, self.plaintext_has_punctuation):
                        plaintext += chr(ascii_num)
                    else:
                        plaintext += "#"
                else:
                    plaintext += "#"

            self.maybe_plaintexts.append(plaintext)

    # Get a list of all words that can be the replacement for a partial plaintext word containing hash signs
    def _get_compatible_words(self, partial_word):
        length = len(partial_word)
        candidates = self.common_words_dict[length]

        # Filter by each known letter position
        for i, char in enumerate(partial_word):
            if char.isalpha():
                candidates = [w for w in candidates if w[i] == char]
                if not candidates:
                    return []

        return candidates

    # Separate the current ciphertext into words using regex, ignore extra spaces
    @staticmethod
    def _split_words(text):
        pattern = re.compile(r'[a-zA-Z#]+')
        result = []

        for match in pattern.finditer(text):
            word = match.group()
            start = match.start()
            result.append((word, start))
        return result

    # Non-destructively checks whether modifying the key so that it produces the given word on the given ciphertext
    # at the given start index results in valid ASCII on all remaining ciphertexts. If it fits, it modifies the key
    # permanently and returns True. Returns False otherwise.
    def _fit_word(self, text_index, word_start, candidate):
        ciphertext = self.ciphertexts[text_index]

        # We will create a "key snippet" here that we will test on all ciphertexts
        # later. This is to make sure that if we apply a dictionary word, all of its
        # letters actually work. This is the only way a word can be fully correct.

        # Since we will use an infinite loop that will go until there are no changes
        # made to the key, we also want to keep track of whether we did any modifications.
        # So, return if the word was able to fit as a boolean.
        maybe_correct_bytes = []
        for i, c in enumerate(candidate):
            cursor = word_start + i
            maybe_correct_bytes.append((cursor, ciphertext[cursor] ^ ord(c)))

        # Now we test...
        for i, byte in maybe_correct_bytes:

            if not all(
                    self._is_english_ascii(ctxt[i] ^ byte,
                                           self.plaintext_has_numbers,
                                           self.plaintext_has_punctuation)
                    for ctxt in self.ciphertexts
            ):
                return False

        # If we are here, the resultant key bytes of the candidate word must have been
        # consistent on the other ciphertexts too. We could validate those are actual words too,
        # but I don't want to make this any slower and this seems enough for now...
        modified = False
        for i, byte in maybe_correct_bytes:
            if self.maybe_key[i] != byte:
                self.maybe_key[i] = byte
                modified = True

        return modified


    def apply_dict_guesses(self):
        """
        Run the common-word dictionary attack and try to fill in all the unknown characters
        represented by hash signs (#) in the current plaintexts list.
        """
        modified = False

        for text_index, text in enumerate(self.maybe_plaintexts):
            for word, start in self._split_words(text):
                candidates = self._get_compatible_words(word.lower())

                for candidate in candidates[:self.number_top_candidates_to_try]:
                    if self._fit_word(text_index, start, candidate):
                        modified = True
                        break

        return modified

    def try_decipher(self, print_results=True):
        """
        :param print_results:
        When set to True, just prints the plaintexts that we were able to recover, one per each line.
        Set to True by default.
        """
        self.no_dict_guess()
        for i in range(self.max_decipher_iters):
            self.update_plaintexts()
            if not self.apply_dict_guesses(): break

        if print_results:
            for plaintext in self.maybe_plaintexts: print(plaintext)